### ISSUE TITLE
SyntaxException on multiple 'IS NOT NULL'

### ISSUE THREAD

**Issue by xfumihiro** [vintikzzz/cassandra_ecto#3]
`where: not(is_nil(value1)) and not(is_nil(value2))`
should be translated into 
`WHERE (value1 is not null) and (value2 is not null)`
instead of
`WHERE (value1 is not null and value2 is not null)`
which raises
`SyntaxException: line 1:100 missing ')' at 'and' (... (value1 is not null [and] value2...)`

**Comment by vintikzzz** [comment]
Hi! According to [docs](https://docs.datastax.com/en/cql/3.3/cql/cql_reference/cqlCreateMaterializedView.html) there shouldn't be brackets at all. So proper variant should be ``WHERE value1 is not null and value2 is not null``
I have fixed it in https://github.com/vintikzzz/cassandra_ecto/commit/569ca53e683f03ea00b271dee48fc6f96c218c1b
Please switch to [v0.4.1](https://github.com/vintikzzz/cassandra_ecto/releases/tag/v0.4.1)
